### ISSUE TITLE
This plugin does not work

### ISSUE THREAD

**Issue by Daydreamer-riri** [KawaiiZapic/PowertoysRunTOTP#6]
Did I do something wrong?

![image](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/70067449/e360da42-1cb8-452b-ae05-e53711f87546)

```
[2024-04-15 11:33:57.2088] [ERROR] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::239]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <TOTP> when query <[>

Exception full name  : System.ArgumentException
Exception message    : Character is not a Base32 character. (Parameter 'c')
Exception stack trace:
   at OtpNet.Base32Encoding.CharToValue(Char c)
   at OtpNet.Base32Encoding.ToBytes(String input)
   at Community.PowerToys.Run.Plugin.TOTP.Main.<>c__DisplayClass17_0.<Query>b__0(KeyEntry totp)
   at Community.PowerToys.Run.Plugin.TOTP.Main.Query(Query query)
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : Community.PowerToys.Run.Plugin.TOTP
Exception target site: Int32 CharToValue(Char)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-04-15 11:33:57.3553] [ERROR] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::239]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <TOTP> when query <[>

Exception full name  : System.ArgumentException
Exception message    : Character is not a Base32 character. (Parameter 'c')
Exception stack trace:
   at OtpNet.Base32Encoding.CharToValue(Char c)
   at OtpNet.Base32Encoding.ToBytes(String input)
   at Community.PowerToys.Run.Plugin.TOTP.Main.<>c__DisplayClass17_0.<Query>b__0(KeyEntry totp)
   at Community.PowerToys.Run.Plugin.TOTP.Main.Query(Query query)
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : Community.PowerToys.Run.Plugin.TOTP
Exception target site: Int32 CharToValue(Char)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------
```

**Comment by KawaiiZapic** [comment]
Your TOTP key maybe invalid, a TOTP key only can be 26 uppercase char and number 2-7 (Base32), I suggesst you use QRCode scanner to get otpauth:// link insteadof edit file mannually to prevent error.
![image](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/45936772/07fe2d99-5b60-44b4-be88-cd86f0200210)

**Comment by Daydreamer-riri** [comment]
I am using a url exported from Google Authenticator.

Thanks for your reply, I will try the method you suggested.

**Comment by KawaiiZapic** [comment]
> I am using a url exported from Google Authenticator.
> 
> Thanks for your reply, I will try the method you suggested.

If you are using Google Auth this should not be happened. Maybe Google update and break something, I'll take a look at it.  

Usually Google auth can export accounts with QR code, you can use another phone or laptop camera to scan it and get a link start withs otp-migrate:// , and this plugin should be able to decode this link.

**Comment by Daydreamer-riri** [comment]
Yes, I used this url 
![Screenshot_20240415-131327.png](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/70067449/c4d6df40-6af8-4f89-b6b5-6cb03a733352)

**Comment by Daydreamer-riri** [comment]
The link I exported seems to start with "otpauth-migration:"

**Comment by Daydreamer-riri** [comment]
I reinstalled the plugin and added optauth link from the launcher, and everything worked fine this time.  This plugin is great!  Thank you for your great work.

**Comment by KawaiiZapic** [comment]
Thanks for your reply! I made an improvement, if the OTP secret you pass to plugin is invalid, the plugin will show a tip telling you the key is invalid instead of crashing.  
![image](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/45936772/2565a85a-10f7-4edf-b5fd-66d98c7eb815)

https://github.com/KawaiiZapic/PowertoysRunTOTP/releases/tag/1.2.4
