### ISSUE TITLE
OpenClipboard Failed 

### ISSUE THREAD

**Issue by LSTANCZYK** [KawaiiZapic/PowertoysRunTOTP#7]
Just encountered an issue. Details below: 

```

Version: 0.84.0.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True
Date: 9/9/2024 4:40:53 PM
Exception:
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at Community.PowerToys.Run.Plugin.TOTP.Main.<>c__DisplayClass13_3.<Query>b__5(ActionContext e)
   at PowerLauncher.ViewModel.MainViewModel.<>c__DisplayClass31_0.<OpenResultsEvent>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at PowerLauncher.ViewModel.MainViewModel.OpenResultsEvent(Object index, Boolean isMouseClick)
   at PowerLauncher.ViewModel.MainViewModel.<InitializeKeyCommands>b__32_10(Object index)
   at PowerLauncher.ViewModel.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by KawaiiZapic** [comment]
I pushed a fix to handle this problem, here is a build with the fixing, please download and test it.  
Plugin now will try copying code to clipboard for 10 times, if still failed, it will pop a message box instead of crashing.  
If the problem still exists, re-open this issue with error message, I'll take a look at it.
 
[TOTP-4376624-x64.zip](https://github.com/user-attachments/files/16939136/TOTP-4376624-x64.zip)

**Comment by LSTANCZYK** [comment]
Worked great. Thank you!
